title: Youtuber 导航 | Youtube 频道推荐 | Youtuber 推荐 | Youtube 中国
email: biezhi.me@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Youtube 运营技巧，中国 Youtube 频道推荐
keywords: youtuber 推荐, 中文Youtube频道, 中文Youtuber, Youtube开箱, Youtube运营, 油管频道
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://u2b.club" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
