title: Youtube 导航 | Youtube 频道推荐 | Youtuber 推荐 | Youtube 中国
email: biezhi.me@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  youtube 导航, Youtube 运营技巧，中国 Youtube 频道推荐
keywords: youtube中文频道排行, youtube优秀中文频道, youtube频道分类, youtube导航, youtuber推荐, 中文youtuber, youtube开箱, youtube运营, 油管频道, 上youtube看什么
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://u2b.club" # the base hostname & protocol for your site, e.g. http://example.com
version: 0.1.2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
